[metadata]
creation_date = "2023/10/11"

[rule]
author = ["LW"]
description = "Insert description here"
from = "now-6m" #Default value, please change as needed
name = "Insert detection name"
note = "Insert analysis notes here"
risk_score = 50
severity = "medium"
tags = ["Example", "Tag"]
type = "eql"
language = "eql"
rule_id = "00000000-0000-0000-0000-000000000420"

query = '''
process where host.os.type == "windows" and event.type == "start" and
  process.name: ("powershell.exe", "pwsh.exe", "powershell_ise.exe") and
  process.command_line : ("*MailboxExportRequest*", "*-Mailbox*-ContentFilter*")
'''


[[rule.threat]] # Example tactic, technique, sub-technique
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1005"
name = "Data from Local System"
reference = "https://attack.mitre.org/techniques/T1005/"
[[rule.threat.technique.subtechnique]]
id = "T1114.002"
name = "Remote Email Collection"
reference = "https://attack.mitre.org/techniques/T1114/002/"

[rule.threat.tactic]
id = "TA0002"
name = "Execution"
reference = "https://attack.mitre.org/tactics/TA0002/"