# This is a basic workflow to help you get started with Actions

name: TOML/Mitre Validation
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          python development/dev_link/tomlval.py
          python development/dev_link/mitre.py
