name: Updating Detections
on:
  push:
    path:
      '**.toml'
  workflow_dispatch:

jobs:
  elastic-detections-all:
    runs-on: ubuntu-latest
    env:
      ELASTIC_KEY: ${{secrets.ELASTIC_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: Run Update Script
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          pip install requests
          python dev_link/update_alert.py