# This is a basic workflow to help you get started with Actions

name: TOML/Mitre Validation
on:
  workflow_dispatch:
jobs:
  toml-mitre-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with :
          python-version: '3.12.4'
      - run: pip install requests
      - run: python dev_link/tomlval.py
      - run: python dev_link/mitre.py
